spring:
  cloud:
    gateway:
      routes:
        - id: hncc_pms_route
          uri: lb://hncc-pms
          predicates:
            - Path=/pms/**
          filters:
            - RewritePath=/dev-api(?<segment>.*),$\{segment}

        - id: hncc_pms_route
          uri: lb://hncc-bms
          predicates:
            - Path=/bms/**
          filters:
            - RewritePath=/dev-api(?<segment>.*),$\{segment}

        - id: hncc_dms_route
          uri: lb://hncc-dms
          predicates:
            - Path=/dms/**
          filters:
            - RewritePath=/dev-api(?<segment>.*),$\{segment}

        - id: RuoYi_image_route
          uri: lb://RuoYi
          predicates:
            - Path=/**
          filters:
            - RewritePath=/dev-api/(?<segment>.*),/$\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



