# 数据源配置
spring:
    datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/hncc-dms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: hncc-dms

mybatis-plus:
    mapper-locations: classpath:/mapper/**/*.xml
    global-config:
        db-config:
            id-type: auto

server:
    port: 10020



eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/